version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Iniciando despliegue para ambiente ${ENVIRONMENT}"
      - cd infrastructure/environments/${ENVIRONMENT}
      - terraform init

  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Despliegue completado en ambiente ${ENVIRONMENT}"
      - terraform output -json > outputs.json

artifacts:
  files:
    - infrastructure/environments/${ENVIRONMENT}/outputs.json
  name: deploy-outputs 